@startuml
!define DARKBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

class device {
+ DeviceConfig config
# AudioSource AudioSource
}

class DeviceConfig{
+particlesystem Repair;
+particlesystem Break;
+AudioClip Break;
+AudioClip Repaired;
}

interface IRepairable{
+ List<Element> RequiredElements()
+ void Repair()
+ void Break()
}

interface IDamagable

device -> IRepairable
IRepairable-> IDamagable
ScriptableObject <-- DeviceConfig  
@enduml