@startuml
@startuml
!define DARKBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

class Team{
+List<Player> players;
+Boat
int Score;

}

class Boat{
+ Inventory Inventory

}

class Inventory{
List<Element> contains
}

class Element{
}

class Player{

IWeapon IWeapon
Element holds

}

class Gun{

}
interface IWeapon{
}

Gun -o IWeapon
@enduml